/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Car_Management_System_Project_With_Gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
